name: CI Pipeline for Flask API

# Trigger the workflow on push and pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run flake8 linter for code quality checks
      - name: Run flake8
        run: |
          flake8 flask_app.py test_api.py

  docker_build:
    name: Docker Build and API Testing
    runs-on: ubuntu-latest
    needs: lint  # This job runs after the lint job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t flask-qa-api .

      # Step 3: Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name flask_qa_api flask-qa-api
          sleep 10  # Wait for the container to start

      # Step 4: Test the API functionality (basic API test with curl)
      - name: Test API with curl
        run: |
          curl -X POST "http://localhost:5000/predict" -H "Content-Type: application/json" -d '{"question": "How is life?", "context": "Life is beautiful."}' | grep -q "beautiful"  # Basic check for correct response

      # Step 5: Run API Unit Tests
      - name: Run Unit Tests
        run: |
          docker exec flask_qa_api python test_api.py

      # Step 6: Stop and remove the Docker container
      - name: Stop and remove Docker container
        run: |
          docker stop flask_qa_api
          docker rm flask_qa_api
